version: '2'
services:
    cluster1-zookeeper-1:
        container_name: cluster1_zookeeper
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 22181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: localhost:22888:23888
            KAFKA_OPTS: '-Dzookeeper.admin.serverPort=8084'
        network_mode: host

    cluster1-kafka-1:
        container_name: cluster1_broker1_19092
        image: confluentinc/cp-kafka:latest
        network_mode: host
        depends_on:
            - cluster1-zookeeper-1
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: localhost:22181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
        ports:
            - 19092:19092

    cluster1-kafka-2:
        container_name: cluster1_broker2_29092
        image: confluentinc/cp-kafka:latest
        network_mode: host
        depends_on:
            - cluster1-zookeeper-1
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: localhost:22181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
        ports:
            - 29092:29092

    cluster1-kafka-3:
        container_name: cluster1_broker3_39092
        image: confluentinc/cp-kafka:latest
        network_mode: host
        depends_on:
            - cluster1-zookeeper-1
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: localhost:22181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
        ports:
            - 39092:39092
